### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by oGalatico** [PresentKim/InventoryMonitor-PMMP#11]
I know this has nothing to do with your plugin, I need more help in this I'm having a mistake in this code for days and I can not find anyone to help me, tell me what I can do to solve it please.

'Server::getInstance()->getScheduler()->cancelTask($this->getTaskId());'

**Comment by PresentKim** [comment]
Sorry for the late reply

Server::getScheduler() method removed at pmmp/PocketMine-MP@9644766
Now, you can get scheduler instance from PluginBase class (like https://github.com/PresentKim/InventoryMonitor-PMMP/commit/f145dc22eab0b606a9d9d5f579177be87595d024)
